version: '3.8'

services:
  web:
    build: .
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - red_sistema
    labels:
      com.example.service: "web"
      maintainer: "giovanni"

  db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sistema.sql:/docker-entrypoint-initdb.d/sistema.sql
    networks:
      - red_sistema
    labels:
      com.example.service: "db"
      maintainer: "giovanni"

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - red_sistema
    labels:
      com.example.service: "phpmyadmin"
      maintainer: "giovanni"

volumes:
  mysql_data:

networks:
  red_sistema:
    driver: bridge
